export let bookCollection = {
  "Contemporary Fiction": [
    {
      title: "The Midnight Library",
      author: "Matt Haig",
      description: "A novel about all the choices that go into a life well lived.",
      price: "378",
      imageUrl: '../assets/img/c-fiction/Tml.jpeg',
      overview: "The Midnight Library follows Nora Seed, a woman who finds herself in a mystical library between life and death. Each book represents a version of her life had she made different choices. The novel explores themes of regret, second chances, and the true meaning of a fulfilling life.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Hardcover, 304 pages",
      publisher: "Viking"
    },
    {
      title: "Normal People",
      author: "Sally Rooney",
      description: "A complex love story between two Irish teenagers into adulthood.",
      price: "308",
      imageUrl: "/assets/img/c-fiction/Np.jpg",
      overview: "Normal People explores the intricacies of a romantic relationship between two teenagers, Connell and Marianne, as they navigate love, friendship, and the pressures of adulthood.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Paperback, 273 pages",
      publisher: "Faber & Faber"
    },
    {
      title: "The Nickel Boys",
      author: "Colson Whitehead",
      description: "A devastating story of abuse at a reform school in Jim Crow-era Florida.",
      price: "311",
      imageUrl: "/assets/img/c-fiction/Nb.jpg",
      overview: "Based on a real reform school in Florida, The Nickel Boys tells the story of two boys sentenced to a hellish institution, examining racism and injustice in America.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Hardcover, 224 pages",
      publisher: "Doubleday"
    },
    {
      title: "Little Fires Everywhere",
      author: "Celeste Ng",
      description: "Intertwined fates of a picture-perfect family and enigmatic mother and daughter.",
      price: "298",
      imageUrl: "/assets/img/c-fiction/Lfe.jpg",
      overview: "Little Fires Everywhere explores the clash of cultures and the complexities of motherhood through the lens of two families in suburban Ohio.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Paperback, 336 pages",
      publisher: "Penguin Press"
    },
    {
      title: "The Overstory",
      author: "Richard Powers",
      description: "An environmental epic about nine Americans and their relationship with trees.",
      price: "346",
      imageUrl: "/assets/img/c-fiction/Overstory.jpg",
      overview: "The Overstory weaves together the lives of multiple characters to highlight humanity's relationship with nature and the urgency of environmentalism.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Hardcover, 502 pages",
      publisher: "W.W. Norton & Company"
    },
    {
      title: "A Little Life",
      author: "Hanya Yanagihara",
      description: "A profound story of trauma, friendship, and perseverance.",
      price: "399",
      imageUrl: "/assets/img/c-fiction/All.jpeg",
      overview: "A Little Life chronicles the lives of four friends in New York City, focusing on the struggles of one of them, Jude St. Francis, and his traumatic past.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Paperback, 736 pages",
      publisher: "Doubleday"
    },
    {
      title: "The Underground Railroad",
      author: "Colson Whitehead",
      description: "A reimagining of the Underground Railroad as a literal subway system.",
      price: "399",
      imageUrl: "/assets/img/c-fiction/Tur.jpeg",
      overview: "This Pulitzer Prize-winning novel follows Cora as she escapes from slavery through an actual underground railroad, facing the horrors of her past and the struggles for freedom.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Hardcover, 336 pages",
      publisher: "Doubleday"
    },
    {
      title: "Circe",
      author: "Madeline Miller",
      description: "A feminist retelling of the Greek myth of Circe.",
      price: "296",
      imageUrl: "/assets/img/c-fiction/Circe.jpeg",
      overview: "Circe presents a fresh take on the story of the witch from the Odyssey, exploring themes of identity, power, and the search for belonging.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Contemporary Fiction",
      format: "Hardcover, 400 pages",
      publisher: "Little, Brown and Company"
    },
  ],
  "Classic Literature": [
    {
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      description: "A powerful exploration of racial injustice in the American South.",
      price: "320",
      imageUrl: "/assets/img/c-literature/Tkam.jpeg",
      overview: "A coming-of-age story set in the racially charged South, focusing on Scout Finch and her father, Atticus, as he defends a black man falsely accused of raping a white woman.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 281 pages",
      publisher: "J.B. Lippincott & Co."
    },
    {
      title: "1984",
      author: "George Orwell",
      description: "A chilling portrayal of a totalitarian future society.",
      price: "99",
      imageUrl: "/assets/img/c-literature/1984.jpg",
      overview: "1984 depicts a dystopian future where government surveillance and propaganda are rampant, and the individual is crushed by the state.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 328 pages",
      publisher: "Secker and Warburg"
    },
    {
      title: "Pride and Prejudice",
      author: "Jane Austen",
      description: "A witty exploration of love and marriage in Georgian England.",
      price: "199",
      imageUrl: "/assets/img/c-literature/PP.jpeg",
      overview: "This novel follows Elizabeth Bennet as she navigates issues of class, marriage, and morality in early 19th-century England.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 279 pages",
      publisher: "T. Egerton"
    },
    {
      title: "One Hundred Years of Solitude",
      author: "Gabriel García Márquez",
      description: "A multi-generational saga of the Buendía family.",
      price: "249",
      imageUrl: "/assets/img/c-literature/Ohys.jpg",
      overview: "This landmark novel chronicles the Buendía family over several generations in the fictional town of Macondo, blending magical realism with historical events.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 417 pages",
      publisher: "Harper & Row"
    },
    {
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      description: "A critique of the American Dream in the Jazz Age.",
      price: "279",
      imageUrl: "/assets/img/c-literature/Tgg.jpg",
      overview: "Set in the Roaring Twenties, The Great Gatsby tells the story of Jay Gatsby and his obsession with the beautiful Daisy Buchanan.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 180 pages",
      publisher: "Charles Scribner's Sons"
    },
    {
      title: "Beloved",
      author: "Toni Morrison",
      description: "A haunting tale of slavery and its aftermath.",
      price: "340",
      imageUrl: "/assets/img/c-literature/Beloved.jpeg",
      overview: "Beloved follows Sethe, a former enslaved woman, as she grapples with the trauma of her past and the ghost of her deceased daughter.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 324 pages",
      publisher: "Alfred A. Knopf"
    },
    {
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      description: "A teenager's alienation in 1950s New York City.",
      price: "220",
      imageUrl: "/assets/img/c-literature/Tcr.jpeg",
      overview: "The Catcher in the Rye follows Holden Caulfield as he navigates the challenges of adolescence and alienation in post-war America.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Classic Literature",
      format: "Paperback, 277 pages",
      publisher: "Little, Brown and Company"
    }
  ],

  "Mystery/Thriller": [
    {
      title: "Gone Girl",
      author: "Gillian Flynn",
      description: "A suspenseful tale of a marriage gone wrong.",
      price: "399",
      imageUrl: "/assets/img/mystery/GG.jpeg",
      overview: "Gone Girl follows the mysterious disappearance of Amy Dunne and the ensuing media frenzy that puts her husband Nick at the center of a police investigation.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 422 pages",
      publisher: "Crown Publishing Group"
    },
    {
      title: "The Girl with the Dragon Tattoo",
      author: "Stieg Larsson",
      description: "A gripping modern mystery involving corruption and murder.",
      price: "499",
      imageUrl: "/assets/img/mystery/Tgdt.jpeg",
      overview: "This novel follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they investigate the decades-old disappearance of a young woman in Sweden.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 465 pages",
      publisher: "Norstedts Förlag"
    },
    {
      title: "The Da Vinci Code",
      author: "Dan Brown",
      description: "A fast-paced thriller filled with secrets and intrigue.",
      price: "299",
      imageUrl: "/assets/img/mystery/Davincicode.jpg",
      overview: "Robert Langdon, a symbologist, is drawn into a conspiracy involving a murder in the Louvre and a quest to uncover hidden truths about the Holy Grail.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 489 pages",
      publisher: "Doubleday"
    },
    {
      title: "The Woman in the Window",
      author: "A.J. Finn",
      description: "A psychological thriller about an agoraphobic woman.",
      price: "349",
      imageUrl: "/assets/img/mystery/Womeninwindow.jpeg",
      overview: "Anna Fox, a reclusive woman confined to her home, becomes obsessed with watching her neighbors and witnesses something shocking that threatens her sanity.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 432 pages",
      publisher: "HarperCollins"
    },
    {
      title: "The Silent Patient",
      author: "Alex Michaelides",
      description: "A psychological thriller about a woman's act of violence.",
      price: "399",
      imageUrl: "/assets/img/mystery/Silentpatient.jpeg",
      overview: "Alicia Berenson, a famous painter, shoots her husband and then stops speaking. A psychotherapist is determined to unravel her silence and discover her motives.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 336 pages",
      publisher: "Celadon Books"
    },
    {
      title: "Big Little Lies",
      author: "Liane Moriarty",
      description: "A tale of murder, friendship, and secrets.",
      price: "379",
      imageUrl: "/assets/img/mystery/Bll.jpeg",
      overview: "Three women’s lives intertwine in this darkly comedic mystery that leads to a shocking murder at a school trivia night.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 460 pages",
      publisher: "Putnam"
    },
    {
      title: "In the Woods",
      author: "Tana French",
      description: "A psychological mystery featuring detective Rob Ryan investigating a chilling case in Dublin.",
      price: "480",
      imageUrl: "/assets/img/mystery/Inthewoods.jpeg",
      overview: "In the Woods follows detective Rob Ryan, who investigates a murder in the same woods where, as a child, he was involved in a traumatic, unsolved incident. As the case unfolds, it becomes clear that the past may hold the key to solving the present mystery.",
      stockAvailability: "In Stock",
      language: "English",
      genre: "Mystery/Thriller",
      format: "Paperback, 429 pages",
      publisher: "Penguin Books"
  }
  
  ],

  "Science Fiction/Fantasy": [
    {
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        description: "A hilarious journey through space and time.",
        price: "348",
        imageUrl: "/assets/img/sci-fi/Guidetogalaxy.jpeg",
        overview: "The Hitchhiker's Guide to the Galaxy follows the misadventures of Arthur Dent, who is taken on an intergalactic journey after Earth is demolished to make way for a hyperspace bypass.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Science Fiction/Fantasy",
        format: "Paperback, 224 pages",
        publisher: "Pan Books"
    },
    {
        title: "Dune",
        author: "Frank Herbert",
        description: "An epic science fiction tale of politics, religion, and ecology.",
        price: "384",
        imageUrl: "/assets/img/sci-fi/dune.jpg",
        overview: "Dune tells the story of Paul Atreides, who becomes embroiled in a complex struggle for control of the desert planet Arrakis, the only source of the universe's most valuable substance, melange.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Science Fiction/Fantasy",
        format: "Hardcover, 688 pages",
        publisher: "Chilton Books"
    },
    {
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        description: "A young musician's quest to become the most powerful wizard in the world.",
        price: "536",
        imageUrl: "/assets/img/sci-fi/Nameofwind.jpg",
        overview: "The Name of the Wind follows Kvothe, a young man who grows up to be a famous wizard and musician. It recounts his adventures as he seeks to learn magic and uncover the truth behind his family's murder.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Fantasy",
        format: "Paperback, 662 pages",
        publisher: "DAW Books"
    },
    {
        title: "Neuromancer",
        author: "William Gibson",
        description: "A groundbreaking cyberpunk novel about hacking and artificial intelligence.",
        price: "372",
        imageUrl: "/assets/img/sci-fi/Neuromancer.jpeg",
        overview: "Neuromancer tells the story of Case, a washed-up computer hacker hired for one last job: to pull off the ultimate hack in a high-tech world where artificial intelligences manipulate reality.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Science Fiction/Fantasy",
        format: "Paperback, 271 pages",
        publisher: "Ace Books"
    },
    {
        title: "The Martian",
        author: "Andy Weir",
        description: "An astronaut's struggle to survive alone on Mars.",
        price: "366",
        imageUrl: "/assets/img/sci-fi/Martian.jpg",
        overview: "The Martian follows astronaut Mark Watney as he uses his ingenuity and spirit to survive on Mars after being left behind by his crew. It's a tale of hope, perseverance, and the will to survive.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Science Fiction",
        format: "Paperback, 369 pages",
        publisher: "Crown Publishing Group"
    },
    {
        title: "The Fifth Season",
        author: "N.K. Jemisin",
        description: "A world where civilization-destroying earthquakes occur every few centuries.",
        price: "440",
        imageUrl: "/assets/img/sci-fi/Fifthseason.jpeg",
        overview: "The Fifth Season is set in a world plagued by seismic activity and follows three women with the power to control the earth. It explores themes of oppression, survival, and the power of community.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Fantasy",
        format: "Paperback, 512 pages",
        publisher: "Orbit"
    },
    {
        title: "Snow Crash",
        author: "Neal Stephenson",
        description: "A mind-bending cyberpunk adventure in a future America.",
        price: "352",
        imageUrl: "/assets/img/sci-fi/Snowcrash.jpeg",
        overview: "Snow Crash follows Hiro Protagonist, a hacker and pizza delivery driver, as he uncovers a virtual drug that is capable of controlling people both in the digital realm and in real life.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Science Fiction/Fantasy",
        format: "Paperback, 480 pages",
        publisher: "Bantam Books"
    },
    {
        title: "The Night Circus",
        author: "Erin Morgenstern",
        description: "A magical competition between two young illusionists.",
        price: "299",
        imageUrl: "/assets/img/sci-fi/Nightcircus.jpeg",
        overview: "The Night Circus tells the story of a mysterious circus that opens only at night and serves as a battleground for two young illusionists bound in a competition of magical skill and creativity.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Fantasy",
        format: "Hardcover, 512 pages",
        publisher: "Doubleday"
    }
],
  "Non-fiction": [
    {
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        description: "A provocative look at the history and future of our species.",
        price: "449",
        imageUrl: "/assets/img/non-fiction/Sapiens.jpeg",
        overview: "Sapiens explores the journey of humankind from the Stone Age to the modern age, examining how shared beliefs, cultures, and technologies have shaped our societies.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Hardcover, 443 pages",
        publisher: "Harper"
    },
    {
        title: "The Immortal Life of Henrietta Lacks",
        author: "Rebecca Skloot",
        description: "The story of HeLa cells and their impact on medical research.",
        price: "352",
        imageUrl: "/assets/img/non-fiction/Theimmortal.jpg",
        overview: "This book tells the true story of Henrietta Lacks, whose cells were taken without her knowledge in 1951, leading to numerous medical breakthroughs.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Paperback, 381 pages",
        publisher: "Crown Publishing Group"
    },
    {
        title: "Quiet: The Power of Introverts in a World That Can't Stop Talking",
        author: "Susan Cain",
        description: "An exploration of introversion in an extrovert-dominated society.",
        price: "437",
        imageUrl: "/assets/img/non-fiction/Quiet.jpg",
        overview: "Quiet challenges the cultural bias against introverts and highlights their contributions to society, emphasizing the importance of both introversion and extroversion.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Hardcover, 368 pages",
        publisher: "Crown Publishing Group"
    },
    {
        title: "The Warmth of Other Suns",
        author: "Isabel Wilkerson",
        description: "An epic tale of America's Great Migration.",
        price: "899",
        imageUrl: "/assets/img/non-fiction/Warmth.jpg",
        overview: "Wilkerson chronicles the migration of African Americans from the rural South to urban centers in the North and West, illustrating its impact on American society.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Hardcover, 640 pages",
        publisher: "Random House"
    },
    {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        description: "An analysis of the two systems that drive the way we think.",
        price: "458",
        imageUrl: "/assets/img/non-fiction/Thinking.jpeg",
        overview: "Kahneman delves into the dual processes of thinking—System 1 (fast) and System 2 (slow)—and how they shape our judgments and decisions.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Hardcover, 512 pages",
        publisher: "Farrar, Straus and Giroux"
    },
    {
        title: "The Devil in the White City",
        author: "Erik Larson",
        description: "Intertwining stories of an architect and a serial killer in 1893 Chicago.",
        price: "599",
        imageUrl: "/assets/img/non-fiction/Devilinwhitecity.jpeg",
        overview: "This narrative nonfiction book juxtaposes the history of the 1893 World's Fair in Chicago with the story of H.H. Holmes, a serial killer who exploited the fair's visitors.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Paperback, 447 pages",
        publisher: "Vintage"
    },
    {
        title: "Bad Blood: Secrets and Lies in a Silicon Valley Startup",
        author: "John Carreyrou",
        description: "The rise and fall of blood-testing startup Theranos.",
        price: "650",
        imageUrl: "/assets/img/non-fiction/Badblood.jpeg",
        overview: "Carreyrou reveals the story behind Theranos and its founder Elizabeth Holmes, detailing the deception that led to the company's downfall.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Hardcover, 352 pages",
        publisher: "Knopf"
    },
    {
        title: "Educated",
        author: "Tara Westover",
        description: "A memoir about a young girl who leaves her survivalist family and goes on to earn a PhD.",
        price: "330",
        imageUrl: "/assets/img/non-fiction/Educated.jpg",
        overview: "Educated chronicles Westover's journey from growing up in a strict and abusive household in rural Idaho to pursuing formal education and discovering the world.",
        stockAvailability: "In Stock",
        language: "English",
        genre: "Non-fiction",
        format: "Hardcover, 334 pages",
        publisher: "Random House"
    }
]
};

